server:
  port: 8081
  
spring:
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true


security:
  oauth2:
    resource:
      token-info-uri: http://127.0.0.1:8080/oauth/check_token
      jwt:
        key-uri: http://127.0.0.1:8080/oauth/token_key
    client:
      client-id: auth-manager
      client-secret: auth-manager

