server:
  port: 8081
  error:
    whitelabel:
      enabled: false


spring:
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 20
      pool-name: HikariCP
      connection-test-query: select 1
      idle-timeout: 30000
      connection-timeout: 60000
#    url: jdbc:h2:file:./server-sample/db/main
    url: jdbc:mysql://localhost:3306/server-sample?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 567711

  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true


security:
  oauth2:
    resource:
      token-info-uri: http://127.0.0.1:8080/oauth/check_token
      jwt:
        #        key-uri: http://127.0.0.1:8080/oauth/token_key
        key-value: 123
    client:
      client-id: auth-manager
      client-secret: auth-manager
